
target 'CocoaLumberjack-RemoteAccess_Example' do
  pod 'CocoaLumberjack-RemoteAccess', :path => '../'

  target 'CocoaLumberjack-RemoteAccess_Tests' do
    pod 'CocoaLumberjack-RemoteAccess', :path => '../'

    
  end
end
